-- Seed current Random Stuff directory items into Supabase.
-- Run this in Supabase SQL Editor after creating public.items.

begin;

truncate table public.items;

insert into public.items (
  id,
  title,
  description,
  website,
  github,
  category,
  tags,
  image,
  is_new,
  sort_order
)
values
  ('websites-react-bits', 'React Bits', 'A huge library of animated React components.', 'https://reactbits.dev', null, 'Websites', array['all']::text[], 'https://reactbits.dev/favicon.ico', false, 0),
  ('softwares-wiztree', 'WizTree', 'Find what''s eating your disk space on Windows.', 'https://diskanalyzer.com', null, 'Softwares', array['windows']::text[], 'https://diskanalyzer.com/favicon.ico', false, 1),
  ('softwares-raycast', 'Raycast', 'The best launcher for macOS. Replaces Spotlight.', 'https://raycast.com', 'https://github.com/raycast', 'Softwares', array['macos']::text[], 'https://www.google.com/s2/favicons?domain=raycast.com&sz=64', false, 2),
  ('scripts-ffmpeg-script', 'Ffmpeg Script', 'Quickly convert MKV to MP4 without losing quality.', '#', null, 'Scripts', array['macos', 'windows', 'linux']::text[], null, false, 3),
  ('scripts-chris-titus-winutil', 'Chris Titus WinUtil', 'The ultimate Windows utility to debloat, update, and fix Windows.', 'https://christitus.com/one-tool-for-everything/', null, 'Scripts', array['windows']::text[], 'https://www.google.com/s2/favicons?domain=christitus.com&sz=64', false, 4),
  ('softwares-playcover', 'PlayCover', 'Run iOS apps and games on Apple Silicon Macs with keyboard support.', 'https://playcover.io', 'https://github.com/PlayCover/PlayCover/', 'Softwares', array['macos']::text[], 'https://github.com/PlayCover.png', false, 5),
  ('websites-fmhy', 'FMHY', 'The largest collection of free stuff on the internet (tools, piracy, etc).', 'https://fmhy.net/', 'https://github.com/fmhy/bookmarks', 'Websites', array['all']::text[], 'https://www.google.com/s2/favicons?domain=fmhy.net&sz=64', false, 6),
  ('softwares-github-store', 'Github Store', 'A free app store to browse and install apps from GitHub releases.', 'https://www.github-store.org/', 'https://github.com/rainxchzed/Github-Store/', 'Softwares', array['all']::text[], 'https://github.com/rainxchzed.png', false, 7),
  ('websites-awesome-swift-apps', 'Awesome Swift Apps', 'A curated list of open-source macOS applications built with Swift.', null, 'https://github.com/jaywcjlove/awesome-swift-macos-apps/', 'Websites', array['macos']::text[], 'https://github.com/jaywcjlove.png', false, 8),
  ('softwares-popcorn-time', 'Popcorn Time', 'Watch movies and TV shows instantly via torrent streaming.', 'https://popcorntime.app', 'https://github.com/popcorntime/popcorntime', 'Softwares', array['macos', 'windows', 'linux']::text[], 'https://github.com/popcorntime.png', false, 9),
  ('softwares-brisk', 'Brisk', 'An ultra-fast, modern download manager for macOS and Linux.', null, 'https://github.com/BrisklyDev/brisk/', 'Softwares', array['macos', 'linux']::text[], 'https://github.com/BrisklyDev.png', false, 10),
  ('websites-cobalt', 'Cobalt', 'Download media from YouTube, Twitter, and more without ads or tracking.', 'https://cobalt.tools/', null, 'Websites', array['all']::text[], 'https://www.google.com/s2/favicons?domain=cobalt.tools&sz=64', false, 11),
  ('softwares-mole', 'Mole', 'A terminal tool for deep macOS cleanup and app uninstallation.', 'https://x.com/HiTw93/status/2037873590461464915', 'https://github.com/tw93/Mole', 'Softwares', array['macos']::text[], 'https://github.com/tw93.png', false, 12),
  ('websites-vert', 'Vert', 'Securely convert files locally in your browser using WebAssembly.', 'https://vert.sh/', 'https://github.com/VERT-sh/VERT', 'Websites', array['all']::text[], 'https://www.google.com/s2/favicons?domain=vert.sh&sz=64', false, 13),
  ('softwares-mounty', 'Mounty', 'A tiny tool to re-mount write-protected NTFS volumes on macOS.', 'https://mounty.app/', 'https://github.com/tuxera/ntfs-3g', 'Softwares', array['macos']::text[], 'https://mounty.app/favicon.ico', false, 14),
  ('websites-isocons', 'Isocons', 'A free collection of customizable isometric icons.', 'https://www.isocons.app/', null, 'Websites', array['all']::text[], 'https://www.google.com/s2/favicons?domain=www.isocons.app&sz=64', false, 15),
  ('softwares-boring-notch', 'Boring Notch', 'Turns your MacBook notch into a dynamic, functional hub.', 'https://theboring.name/', 'https://github.com/TheBoredTeam/boring.notch/?tab=readme-ov-file', 'Softwares', array['macos']::text[], 'https://github.com/TheBoredTeam.png', false, 16),
  ('softwares-darkwrite', 'Darkwrite', 'A distraction-free, eye-candy note-taking and to-do app.', 'https://darkwrite.app/', 'https://github.com/astudentinearth/darkwrite', 'Softwares', array['all']::text[], 'https://www.google.com/s2/favicons?domain=darkwrite.app&sz=64', false, 17),
  ('softwares-utm', 'UTM', 'Run virtual machines (Windows, Linux) on iOS and macOS.', 'https://getutm.app', 'https://github.com/utmapp/UTM', 'Softwares', array['macos']::text[], 'https://github.com/utmapp.png', false, 18),
  ('softwares-winapps', 'WinApps', 'Run Windows apps like Office and Adobe on Linux seamlessly.', null, 'https://github.com/winapps-org/winapps', 'Softwares', array['linux']::text[], 'https://github.com/winapps-org.png', false, 19),
  ('websites-edclub', 'EdClub', 'Educational platform for typing, vocabulary, and more.', 'https://www.edclub.com/sportal/', null, 'Websites', array['all']::text[], 'https://www.google.com/s2/favicons?domain=www.edclub.com&sz=64', false, 20),
  ('scripts-mas', 'MAS', 'Microsoft Activation Scripts - Open source Windows/Office activator.', 'https://massgrave.dev', 'https://github.com/massgravel/Microsoft-Activation-Scripts', 'Scripts', array['windows']::text[], 'https://github.com/massgravel.png', false, 21),
  ('softwares-niri', 'niri', 'A scrollable-tiling Wayland compositor.', 'https://niri-wm.github.io/niri/', 'https://github.com/YaLTeR/niri', 'Softwares', array['linux']::text[], 'https://github.com/YaLTeR.png', false, 22),
  ('softwares-spicetify-cli', 'Spicetify CLI', 'Command-line tool to customize the Spotify desktop app.', 'https://spicetify.app', 'https://github.com/spicetify/cli', 'Softwares', array['macos', 'windows', 'linux']::text[], 'https://github.com/spicetify.png', false, 23),
  ('scripts-win11debloat', 'Win11Debloat', 'Debloat and tweak Windows 11.', null, 'https://github.com/Raphire/Win11Debloat', 'Scripts', array['windows']::text[], 'https://github.com/Raphire.png', false, 24),
  ('softwares-dockdoor', 'DockDoor', 'Dock alternative for macOS.', 'https://dockdoor.net/', 'https://github.com/ejbills/DockDoor', 'Softwares', array['macos']::text[], 'https://www.google.com/s2/favicons?domain=dockdoor.net&sz=64', false, 25),
  ('softwares-shine', 'Shine', 'Open-source project from Blade04208.', null, 'https://github.com/Blade04208/shine/', 'Softwares', array['all']::text[], 'https://github.com/Blade04208.png', false, 26),
  ('softwares-gemini-watermark-remover', 'Gemini Watermark Remover', 'Watermark removal tool.', 'https://pilio.ai/gemini-watermark-remover', 'https://github.com/journey-ad/gemini-watermark-remover', 'Softwares', array['all']::text[], 'https://github.com/journey-ad.png', false, 27),
  ('softwares-shadps4', 'shadPS4', 'PlayStation 4 emulator.', 'https://shadps4.net/', 'https://github.com/shadps4-emu/shadPS4', 'Softwares', array['windows', 'linux']::text[], 'https://github.com/shadps4-emu.png', false, 28),
  ('softwares-mate-engine', 'Mate Engine', 'Game engine project.', 'https://store.steampowered.com/app/3625270/MateEngine/', 'https://github.com/shinyflvre/Mate-Engine', 'Softwares', array['all']::text[], 'https://github.com/shinyflvre.png', false, 29),
  ('softwares-cline', 'Cline', 'Open-source AI coding assistant.', 'https://marketplace.visualstudio.com/items?itemName=saoudrizwan.claude-dev', 'https://github.com/cline/cline', 'Softwares', array['all']::text[], 'https://github.com/cline.png', false, 30),
  ('softwares-facefusion', 'FaceFusion', 'Face swap and enhancement toolkit.', 'https://facefusion.io', 'https://github.com/allenk/facefusion', 'Softwares', array['all']::text[], 'https://github.com/allenk.png', false, 31),
  ('softwares-droppy', 'Droppy', 'Self-hosted file sharing app.', null, 'https://github.com/iordv/Droppy', 'Softwares', array['all']::text[], 'https://github.com/iordv.png', false, 32),
  ('softwares-open-researcher', 'Open Researcher', 'Automated research assistant.', null, 'https://github.com/firecrawl/open-researcher', 'Softwares', array['all']::text[], 'https://github.com/firecrawl.png', false, 33),
  ('scripts-cloudflare-error-page', 'Cloudflare Error Page', 'Custom Cloudflare error page template.', 'https://virt.moe/cferr/editor/', 'https://github.com/donlon/cloudflare-error-page', 'Scripts', array['all']::text[], 'https://github.com/donlon.png', false, 34),
  ('softwares-lm-studio', 'LM Studio', 'Run local LLMs on your machine.', 'https://lmstudio.ai/', 'https://github.com/lmstudio-ai', 'Softwares', array['macos', 'windows', 'linux']::text[], 'https://lmstudio.ai/favicon.ico', false, 35),
  ('websites-shader-gradient', 'Shader Gradient', 'Generate shader-style gradients.', 'https://shadergradient.co/', null, 'Websites', array['all']::text[], 'https://www.google.com/s2/favicons?domain=shadergradient.co&sz=64', false, 36),
  ('softwares-openscreen', 'OpenScreen', 'Screen sharing and remote control.', 'https://openscreen.vercel.app', 'https://github.com/siddharthvaddem/openscreen', 'Softwares', array['all']::text[], 'https://github.com/siddharthvaddem.png', false, 37),
  ('softwares-finetune', 'FineTune', 'A macOS menu bar app for per-app volume control, multi-device output, audio routing, and 10-band EQ.', null, 'https://github.com/ronitsingh10/FineTune', 'Softwares', array['macos']::text[], 'https://github.com/ronitsingh10.png', false, 38),
  ('softwares-net-bar', 'Net-Bar', 'Network status bar app.', null, 'https://github.com/iad1tya/Net-Bar', 'Softwares', array['all']::text[], 'https://github.com/iad1tya.png', false, 39),
  ('websites-ear-web', 'Ear (web)', 'Unofficial web app to control Nothing/CMF audio devices on PC/Mac.', 'https://earweb.bttl.xyz/', 'https://github.com/radiance-project/ear-web/issues', 'Websites', array['all']::text[], 'https://earweb.bttl.xyz/favicon.ico', false, 40),
  ('softwares-scrcpy-gui', 'Scrcpy GUI', 'A modern, high-performance Windows GUI for scrcpy.', null, 'https://github.com/kil0bit-kb/scrcpy-gui', 'Softwares', array['windows']::text[], 'https://github.com/kil0bit-kb.png', false, 41),
  ('softwares-codexbar', 'CodexBar', 'MacOS menu bar app to track OpenAI/Claude usage quotas.', 'https://codexbar.app', 'https://github.com/steipete/CodexBar', 'Softwares', array['macos']::text[], 'https://github.com/steipete.png', false, 42),
  ('websites-excalidraw', 'Excalidraw', 'Virtual collaborative whiteboard with hand-drawn feel diagrams.', 'https://excalidraw.com', null, 'Websites', array['all']::text[], 'https://excalidraw.com/favicon.ico', false, 43),
  ('websites-corca', 'Corca', 'Fast, intuitive math editor with real-time collaboration and LaTeX export.', 'https://corca.app', null, 'Websites', array['all']::text[], 'https://corca.app/favicon.ico', false, 44),
  ('softwares-quick-subtitles', 'Quick Subtitles', 'Generate subtitles for videos in seconds on iOS.', 'https://apps.apple.com/us/app/quick-subtitles/id6747410609', null, 'Softwares', array['ios']::text[], 'https://www.google.com/s2/favicons?domain=apps.apple.com&sz=64', false, 45),
  ('softwares-transmission', 'Transmission', 'Fast, easy, and free BitTorrent client for Mac, Windows, and Linux.', 'https://transmissionbt.com', 'https://github.com/transmission/transmission/issues', 'Softwares', array['macos', 'windows', 'linux']::text[], 'https://github.com/transmission.png', false, 46),
  ('websites-ilovepdf', 'iLovePDF', 'Free online tools to merge, split, compress, and convert PDFs.', 'https://www.ilovepdf.com/', null, 'Websites', array['all']::text[], 'https://www.ilovepdf.com/favicon.ico', false, 47),
  ('softwares-mini-agent', 'Mini-Agent', 'Open-source agent framework from MiniMax-AI.', 'https://www.minimax.io/', 'https://github.com/MiniMax-AI/Mini-Agent', 'Softwares', array['all']::text[], 'https://github.com/MiniMax-AI.png', false, 48),
  ('softwares-bettercapture', 'BetterCapture', 'The macOS screen recorder for the rest of us - always free and open source with a native look and feel.', 'https://bettercapture.app/', 'https://github.com/jsattler/BetterCapture', 'Softwares', array['macos']::text[], 'https://github.com/jsattler.png', false, 49),
  ('softwares-hidden', 'Hidden', 'An ultra-light MacOS utility that helps hide menu bar icons.', 'https://d.foundation/opensource', 'https://github.com/dwarvesf/hidden', 'Softwares', array['macos']::text[], 'https://github.com/dwarvesf.png', false, 50),
  ('softwares-iina', 'IINA', 'The modern video player for macOS.', 'https://iina.io', 'https://github.com/iina/iina', 'Softwares', array['macos']::text[], 'https://github.com/iina.png', false, 51),
  ('websites-torph', 'Torph', 'Dependency-free animated text component.', 'https://torph.lochie.me/', 'https://github.com/lochie/torph', 'Websites', array['all']::text[], 'https://torph.lochie.me/og.png', false, 52),
  ('websites-scrollbar', 'Scrollbar', 'Simple online scrollbar editor.', 'https://scrollbar.app', 'https://github.com/henripar/scrollbar', 'Websites', array['all']::text[], 'https://github.com/henripar.png', false, 53),
  ('softwares-bentopdf', 'BentoPDF', 'A Privacy First PDF Toolkit.', 'https://bentopdf.com/', 'https://github.com/alam00000/bentopdf', 'Softwares', array['all']::text[], 'https://github.com/alam00000.png', false, 54),
  ('softwares-ps4-game-scraper', 'PS4 Game Scraper', 'PS4 Game Scraper.', null, 'https://github.com/NookieAI/PS4-Game-Scraper', 'Softwares', array['all']::text[], 'https://github.com/NookieAI.png', false, 55),
  ('softwares-copycat-clipboard', 'CopyCat Clipboard', 'An intuitive clipboard manager designed to enhance your workflow and seamlessly switch between documents, apps, and devices.', 'https://www.entilitystudio.com/copycat-clipboard', 'https://github.com/raj457036/CopyCat-Clipboard', 'Softwares', array['all']::text[], 'https://github.com/raj457036.png', false, 56),
  ('websites-sileo', 'Sileo', 'Beautiful Toast Notifications for React.', 'https://sileo.aaryan.design/', 'https://github.com/hiaaryan/sileo', 'Websites', array['all']::text[], 'https://sileo.aaryan.design/favicon.ico', false, 57),
  ('softwares-battery-toolkit', 'Battery-Toolkit', 'Control the platform power state of your Apple Silicon Mac.', null, 'https://github.com/mhaeuser/Battery-Toolkit', 'Softwares', array['macos']::text[], 'https://github.com/mhaeuser.png', false, 58),
  ('softwares-magicpods', 'MagicPods', 'Add little magic to your Airpods on Windows.', 'https://magicpods.app', 'https://github.com/steam3d/MagicPods-Windows', 'Softwares', array['windows']::text[], 'https://github.com/steam3d.png', false, 59),
  ('websites-ipsw-downloads', 'IPSW Downloads', 'Download current and previous versions of Apple''s iOS, iPadOS, macOS, watchOS, tvOS, audioOS and visionOS firmware.', 'https://ipsw.me/', null, 'Websites', array['all']::text[], 'https://ipsw.me/favicon.ico', false, 60),
  ('websites-carbon-design-system', 'Carbon Design System', 'IBM''s open source design system for products and digital experiences.', 'https://www.carbondesignsystem.com', 'https://github.com/carbon-design-system/carbon', 'Websites', array['all']::text[], 'https://github.com/carbon-design-system.png', false, 61),
  ('websites-poke', 'Poke', 'A free software YouTube front-end, translator, map app, and more! All-in-one privacy app.', 'https://poketube.fun/', 'https://github.com/TecharoHQ/anubis', 'Websites', array['all']::text[], 'https://poketube.fun/favicon.ico', false, 62),
  ('softwares-noutube-desktop', 'NouTube Desktop', 'Ad-free YouTube desktop application.', null, 'https://github.com/nonbili/NouTube-Desktop', 'Softwares', array['macos', 'windows', 'linux']::text[], 'https://github.com/nonbili.png', false, 63),
  ('softwares-noutube', 'NouTube', 'Ad-free YouTube client.', null, 'https://github.com/nonbili/NouTube', 'Softwares', array['all']::text[], 'https://github.com/nonbili.png', false, 64),
  ('websites-lucide-animated', 'Lucide Animated', 'Beautiful animated icons for Lucide.', 'https://lucide-animated.com/', 'https://github.com/pqoqubbw/icons', 'Websites', array['all']::text[], 'https://lucide-animated.com/favicon.ico', false, 65),
  ('scripts-scrapy', 'Scrapy', 'A fast high-level web crawling and scraping framework for Python.', 'https://scrapy.org', 'https://github.com/scrapy/scrapy', 'Scripts', array['all']::text[], 'https://github.com/scrapy.png', false, 66),
  ('websites-the-component-gallery', 'The Component Gallery', 'A collection of components from the best Design Systems.', 'https://component.gallery/', 'https://github.com/elastic/eui', 'Websites', array['all']::text[], 'https://www.google.com/s2/favicons?domain=component.gallery&sz=64', false, 67),
  ('softwares-metrolist', 'Metrolist', 'A simple to-do list taking design cues from the Metro design language.', 'https://metrolist.cc/', 'https://github.com/MetrolistGroup/Metrolist', 'Softwares', array['android']::text[], 'https://github.com/MetrolistGroup.png', false, 68),
  ('softwares-karaoke-eternal', 'Karaoke Eternal', 'Open karaoke party system.', 'https://www.karaoke-eternal.com', 'https://github.com/bhj/KaraokeEternal', 'Softwares', array['all']::text[], 'https://github.com/bhj.png', false, 69),
  ('websites-shadcn-admin', 'Shadcn Admin', 'Admin Dashboard UI built with Shadcn and Vite.', 'https://shadcn-admin.netlify.app/', 'https://github.com/satnaing/shadcn-admin', 'Websites', array['all']::text[], 'https://github.com/satnaing.png', false, 70),
  ('softwares-flycut-caption', 'FlyCut Caption', 'A complete video subtitle editing React component with AI-powered speech recognition and visual editing capabilities.', 'https://caption.flycut.co', 'https://github.com/x007xyz/flycut-caption', 'Softwares', array['all']::text[], 'https://github.com/x007xyz.png', false, 71),
  ('websites-awesome-self-hosted', 'Awesome Self-Hosted', 'A list of Free Software network services and web applications which can be hosted on your own servers.', 'https://awesome-selfhosted.net/', 'https://github.com/awesome-selfhosted/awesome-selfhosted', 'Websites', array['all']::text[], 'https://github.com/awesome-selfhosted.png', false, 72),
  ('softwares-winshot', 'WinShot', 'A Windows screenshot tool with annotation, crop, and export features.', 'http://winshot.claudekit.cc/', 'https://github.com/mrgoonie/winshot', 'Softwares', array['windows']::text[], 'https://github.com/mrgoonie.png', false, 73),
  ('softwares-stats', 'Stats', 'macOS system monitor in your menu bar.', 'https://mac-stats.com', 'https://github.com/exelban/stats', 'Softwares', array['macos']::text[], 'https://github.com/exelban.png', false, 74),
  ('websites-api-mega-list', 'API Mega List', 'A powerhouse collection of APIs you can start using immediately to build everything from simple automations to full-scale applications.', null, 'https://github.com/cporter202/API-mega-list', 'Websites', array['all']::text[], 'https://github.com/cporter202.png', false, 75),
  ('softwares-gopeed', 'Gopeed', 'A modern download manager that supports all platforms. Built with Golang and Flutter.', 'https://gopeed.com', 'https://github.com/GopeedLab/gopeed', 'Softwares', array['all']::text[], 'https://github.com/GopeedLab.png', false, 76),
  ('softwares-bulk-crap-uninstaller', 'Bulk Crap Uninstaller', 'Remove large amounts of unwanted applications quickly.', 'https://www.bcuninstaller.com/', 'https://github.com/Klocman/Bulk-Crap-Uninstaller', 'Softwares', array['windows']::text[], 'https://github.com/Klocman.png', false, 77),
  ('websites-delphi-tools', 'Delphi Tools', 'A collection of small, low stakes and low effort web tools including calculators, converters, and generators.', 'https://delphi.tools/', 'https://github.com/1612elphi/delphitools', 'Websites', array['all']::text[], 'https://delphi.tools/favicon.ico', false, 78),
  ('softwares-anythingllm', 'AnythingLLM', 'The all-in-one AI productivity accelerator. On device and privacy first with no annoying setup or configuration.', 'https://anythingllm.com', 'https://github.com/Mintplex-Labs/anything-llm', 'Softwares', array['all']::text[], 'https://github.com/Mintplex-Labs.png', false, 79),
  ('softwares-llmfit', 'LLMFit', 'Hundreds of models & providers. One command to find what runs on your hardware.', null, 'https://github.com/AlexsJones/llmfit', 'Softwares', array['all']::text[], 'https://github.com/AlexsJones.png', false, 80),
  ('softwares-onyx', 'Onyx', 'Open Source AI Platform - AI Chat with advanced features that works with every LLM.', 'https://www.onyx.app', 'https://github.com/onyx-dot-app/onyx', 'Softwares', array['all']::text[], 'https://github.com/onyx-dot-app.png', false, 81),
  ('softwares-jan', 'Jan', 'An open source alternative to ChatGPT that runs 100% offline on your computer.', 'https://jan.ai', 'https://github.com/janhq/jan/releases/latest', 'Softwares', array['macos', 'windows', 'linux']::text[], 'https://github.com/janhq.png', true, 82),
  ('websites-flow', 'Flow', 'Google Labs Flow tool for AI.', 'https://labs.google/fx/tools/flow', null, 'Websites', array['all']::text[], 'https://labs.google/favicon.ico', true, 83),
  ('softwares-worldmonitor', 'WorldMonitor', 'Real-time global intelligence dashboard. AI-powered news aggregation, geopolitical monitoring, and infrastructure tracking.', 'https://worldmonitor.app', null, 'Softwares', array['all']::text[], 'https://github.com/koala73.png', true, 84),
  ('websites-penpot', 'Penpot', 'The open-source design tool for design and code collaboration.', 'https://penpot.app', 'https://github.com/penpot/penpot', 'Websites', array['all']::text[], 'https://github.com/penpot.png', true, 85),
  ('scripts-visual-explainer', 'Visual Explainer', 'Agent skill that generates rich HTML pages or slide decks for diagrams, diff reviews, plan audits, data tables, and project recaps.', null, 'https://github.com/nicobailon/visual-explainer', 'Scripts', array['all']::text[], 'https://github.com/nicobailon.png', true, 86)
on conflict (id) do update set
  title = excluded.title,
  description = excluded.description,
  website = excluded.website,
  github = excluded.github,
  category = excluded.category,
  tags = excluded.tags,
  image = excluded.image,
  is_new = excluded.is_new,
  sort_order = excluded.sort_order;

commit;
